import subprocess as sp

sp.call(["ffmpeg",
         "-i", "./videos/alan.mp4",
         "-i", "./videos/alan.mp4",
         "-i", "./videos/alan.mp4",
         "-filter_complex", "copy[v1out]",
         "-filter_complex", "scale=w=1280:h=720[v2out]",
         "-filter_complex", "scale=w=640:h=360[v3out]",
         "-map", "[v1out]", "-c:v:0", "libx264", "-x264-params",
         f"\"nal-hrd=cbr:force-cfr=1\"", "-b:v:0", "5M", "-maxrate:v:0", "5M",
         "-minrate:v:0", "5M", "-bufsize:v:0", "10M", "-preset", "slow",
         "-g", "48", "-sc_threshold", "0", "-keyint_min", "48",
         "-map", "[v2out]", "-c:v:1", "libx264", "-x264-params",
         f"\"nal-hrd=cbr:force-cfr=1\"", "-b:v:1", "3M", "-maxrate:v:1", "3M",
         "-minrate:v:1", "3M", "-bufsize:v:1", "3M", "-preset", "slow",
         "-g", "48", "-sc_threshold", "0", "-keyint_min", "48",
         "-map", "[v3out]", "-c:v:2", "libx264", "-x264-params",
         f"\"nal-hrd=cbr:force-cfr=1\"", "-b:v:2", "1M", "-maxrate:v:2", "1M",
         "-minrate:v:2", "1M", "-bufsize:v:2", "1M", "-preset", "slow",
         "-g", "48", "-sc_threshold", "0", "-keyint_min", "48",
         "-map", "a:0", "-c:a:0", "aac", "-b:a:0", "96k", "-ac", "2",
         "-map", "a:0", "-c:a:1", "aac", "-b:a:1", "96k", "-ac", "2",
         "-map", "a:0", "-c:a:2", "aac", "-b:a:2", "48k", "-ac", "2",
         "-f", "hls", "-hls_time", "2", "-hls_playlist_type", "vod",
         "-hls_flags", "independent_segments", "-hls_segment_type", "mpegts",
         "-hls_segment_filename", "./outputs/ex1/stream_%v/data%02d.ts",
         "-master_pl_name", "master.m3u8", "./outputs/ex1/stream_%v.m3u8"])
